<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "orders".
 *
 * @property int $id
 * @property string $name
 * @property string $number
 * @property string $day
 * @property string $time
 * @property int $room_id
 *
 * @property Rooms $room
 */
class Orders extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'orders';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['checkIn','checkOut', 'time'], 'safe'],
            [['room_id'], 'required'],
            [['room_id'], 'integer'],
            [['name', 'number'], 'string', 'max' => 255],
            [['room_id'], 'exist', 'skipOnError' => true, 'targetClass' => Rooms::className(), 'targetAttribute' => ['room_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя клиента',
            'number' => 'Телефон',
            'checkIn' => 'День, на который бронируется',
            'checkOut' => 'День выезда',
            'time' => 'Время бронирования',
            'room_id' => 'Номер',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRoom()
    {
        return $this->hasOne(Rooms::className(), ['id' => 'room_id']);
    }

    public function afterFind()
    {
        parent::afterFind();
        $this->time = date("h:i:s Y-m-d", strtotime($this->time));
        $this->checkIn = date("Y-m-d", strtotime($this->checkIn));
        $this->checkOut = date("Y-m-d", strtotime($this->checkOut));
    }

    public function beforeSave($insert)
    {
        $this->time = date("Y-m-d h:i:s");
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
